---
- hosts: all
  become: yes
  tasks:
    - name: Atualiza pacotes
      apt:
        update_cache: yes

    - name: Instala dependências do Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present

    - name: Adiciona chave GPG do Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adiciona repositório Docker
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
        state: present

    - name: Instala Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest

    - name: Habilita e inicia Docker
      systemd:
        name: docker
        enabled: yes
        state: started

- hosts: manager
  become: yes
  tasks:
    - name: Inicializa o Docker Swarm
      shell: docker swarm init --advertise-addr 192.168.1.2
      register: swarm_init_output
      ignore_errors: yes

    - name: Gera token do swarm
      shell: docker swarm join-token worker -q
      register: swarm_token

    - name: Cria script para os workers
      copy:
        dest: /vagrant/swarm_join.sh
        content: |
          #!/bin/bash
          docker swarm join --token {{ swarm_token.stdout }} 192.168.1.2:2377
        mode: '0755'

- hosts: workers
  become: yes
  tasks:
    - name: Espera o token ser criado
      wait_for:
        path: /vagrant/swarm_join.sh
        state: present

    - name: Executa o script de join
      shell: bash /vagrant/swarm_join.sh
